---
title: "Untitled"
output: html_document
date: "2025-06-11"
---

```{r}

library(dplyr)

library(ggplot2)

library(readr)

```



```{r}

amazondf <- read.csv('C:\\Users\\haozh\\Desktop\\buttress_root\\buttress_plot_pixel_aggregate_20251219.csv');

names(amazondf)



#cooccurdf <- read.csv('C:\\Users\\haozh\\Desktop\\buttress_root\\cooccuring_plots_comp_20241210.csv')
```

```{r}
amazondf <- amazondf %>%
   dplyr::select(matches(
    'CHELSA|SG|Canopy|random|pixel|Earth|Depth|Fire|Land|Nitrogen|Olsen|Organic|PET|WWF|World|fraction|buttress|wind|Distance'
  ))%>%
  mutate(longitude = pixellon,
         latitude = pixellat)


amazondf <- amazondf[complete.cases(amazondf),]
```


```{r}
amazondf %>%
  filter(meanfraction>0)%>%
  nrow()
amazondf %>%
  filter(buttressbinary == 0)%>%
  nrow()


```



```{r}

for(i in 1:100){

set.seed(i)
  
tropdf <- amazondf %>%
  #filter(fraction==0)%>%
  filter(WWF_Biome %in% c(1,2,3,7))%>%
  mutate(majorbiome = 'Tropical')







tempdf <- amazondf %>%
  filter(WWF_Biome %in% c(4,5,8,12))%>%
  sample_n(round(nrow(tropdf)*22/50))%>%
  mutate(majorbiome = 'Temperate')




borealdf <- amazondf %>%
  filter(WWF_Biome %in% c(6,10,11))%>%
  #sample_n(round(nrow(tropdf)*21/50))%>%
  mutate(majorbiome = 'Boreal')




drydf <- amazondf %>%
  filter(WWF_Biome %in% c(9,13))%>%
  sample_n(round(nrow(tropdf)*7/50))%>%
  mutate(majorbiome = 'Arid_and_other')


alldf <- rbind(tropdf, tempdf, borealdf, drydf)




alldf <- alldf %>%
  mutate(fold = (random%%10)+1,
         seed = i)


write_csv(alldf,paste0('C:\\Users\\haozh\\Desktop\\buttress_root\\data\\subsample\\subsampled_buttress_comp_seed_',i,'_20251219.csv'))

}
```




```{r}

setwd('C:\\Users\\haozh\\Desktop\\buttress_root\\data\\subsample')

files <- list.files(pattern = '\\_20251219.csv')

```


```{r}
setwd('C:\\Users\\haozh\\Desktop\\buttress_root\\data\\subsample')
alltables <- lapply(files, read.csv, header = TRUE)


```


```{r}

alldf <- do.call(rbind, alltables)

```


```{r}

write_csv(alldf, 'C:\\Users\\haozh\\Desktop\\buttress_root\\data\\all_subsample_buttress_comp_20251219.csv')


```



